<?php if($this->success) {?>
    <div class="alert alert-success">Продукт добавлен!</div>
<?php } ?>
<?php
$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formRow($this->form->get('product')->get('id'));
echo $this->formRow($this->form->get('product')->get('name'));
echo $this->formRow($this->form->get('product')->get('stock'));
echo $this->formSubmit($this->form->get('submit'));
echo $this->form()->closeTAg();